//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapRSIClient.CowService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cow", Namespace="http://schemas.datacontract.org/2004/07/RSI.Model")]
    [System.SerializableAttribute()]
    public partial class Cow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapRSIClient.CowService.CowBreed CowBreedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfCalvingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapRSIClient.CowService.CowBreed CowBreed {
            get {
                return this.CowBreedField;
            }
            set {
                if ((this.CowBreedField.Equals(value) != true)) {
                    this.CowBreedField = value;
                    this.RaisePropertyChanged("CowBreed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfCalving {
            get {
                return this.DateOfCalvingField;
            }
            set {
                if ((this.DateOfCalvingField.Equals(value) != true)) {
                    this.DateOfCalvingField = value;
                    this.RaisePropertyChanged("DateOfCalving");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagNumber {
            get {
                return this.TagNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TagNumberField, value) != true)) {
                    this.TagNumberField = value;
                    this.RaisePropertyChanged("TagNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CowBreed", Namespace="http://schemas.datacontract.org/2004/07/RSI")]
    public enum CowBreed : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Charolaise = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wagyu = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uckermärker = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Angus = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WelshBlack = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hereford = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CowService.ICowService")]
    public interface ICowService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICowService/GetAllCows", ReplyAction="http://tempuri.org/ICowService/GetAllCowsResponse")]
        SoapRSIClient.CowService.Cow[] GetAllCows();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICowService/GetAllCows", ReplyAction="http://tempuri.org/ICowService/GetAllCowsResponse")]
        System.Threading.Tasks.Task<SoapRSIClient.CowService.Cow[]> GetAllCowsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICowService/GetCowInfo", ReplyAction="http://tempuri.org/ICowService/GetCowInfoResponse")]
        SoapRSIClient.CowService.Cow GetCowInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICowService/GetCowInfo", ReplyAction="http://tempuri.org/ICowService/GetCowInfoResponse")]
        System.Threading.Tasks.Task<SoapRSIClient.CowService.Cow> GetCowInfoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICowService/AddCow", ReplyAction="http://tempuri.org/ICowService/AddCowResponse")]
        bool AddCow(string name, SoapRSIClient.CowService.CowBreed cowBreed, System.DateTime dateOfBirth, System.DateTime dateOfCalving, string tagNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICowService/AddCow", ReplyAction="http://tempuri.org/ICowService/AddCowResponse")]
        System.Threading.Tasks.Task<bool> AddCowAsync(string name, SoapRSIClient.CowService.CowBreed cowBreed, System.DateTime dateOfBirth, System.DateTime dateOfCalving, string tagNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICowService/RemoveCow", ReplyAction="http://tempuri.org/ICowService/RemoveCowResponse")]
        bool RemoveCow(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICowService/RemoveCow", ReplyAction="http://tempuri.org/ICowService/RemoveCowResponse")]
        System.Threading.Tasks.Task<bool> RemoveCowAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICowService/UpdateCow", ReplyAction="http://tempuri.org/ICowService/UpdateCowResponse")]
        bool UpdateCow(int id, string name, SoapRSIClient.CowService.CowBreed cowBreed, System.DateTime dateOfBirth, System.DateTime dateOfCalving, string tagNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICowService/UpdateCow", ReplyAction="http://tempuri.org/ICowService/UpdateCowResponse")]
        System.Threading.Tasks.Task<bool> UpdateCowAsync(int id, string name, SoapRSIClient.CowService.CowBreed cowBreed, System.DateTime dateOfBirth, System.DateTime dateOfCalving, string tagNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICowService/GetCowsNearToCalving", ReplyAction="http://tempuri.org/ICowService/GetCowsNearToCalvingResponse")]
        SoapRSIClient.CowService.Cow[] GetCowsNearToCalving();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICowService/GetCowsNearToCalving", ReplyAction="http://tempuri.org/ICowService/GetCowsNearToCalvingResponse")]
        System.Threading.Tasks.Task<SoapRSIClient.CowService.Cow[]> GetCowsNearToCalvingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICowService/GetCowsNearToDryOff", ReplyAction="http://tempuri.org/ICowService/GetCowsNearToDryOffResponse")]
        SoapRSIClient.CowService.Cow[] GetCowsNearToDryOff();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICowService/GetCowsNearToDryOff", ReplyAction="http://tempuri.org/ICowService/GetCowsNearToDryOffResponse")]
        System.Threading.Tasks.Task<SoapRSIClient.CowService.Cow[]> GetCowsNearToDryOffAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICowServiceChannel : SoapRSIClient.CowService.ICowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CowServiceClient : System.ServiceModel.ClientBase<SoapRSIClient.CowService.ICowService>, SoapRSIClient.CowService.ICowService {
        
        public CowServiceClient() {
        }
        
        public CowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SoapRSIClient.CowService.Cow[] GetAllCows() {
            return base.Channel.GetAllCows();
        }
        
        public System.Threading.Tasks.Task<SoapRSIClient.CowService.Cow[]> GetAllCowsAsync() {
            return base.Channel.GetAllCowsAsync();
        }
        
        public SoapRSIClient.CowService.Cow GetCowInfo(int id) {
            return base.Channel.GetCowInfo(id);
        }
        
        public System.Threading.Tasks.Task<SoapRSIClient.CowService.Cow> GetCowInfoAsync(int id) {
            return base.Channel.GetCowInfoAsync(id);
        }
        
        public bool AddCow(string name, SoapRSIClient.CowService.CowBreed cowBreed, System.DateTime dateOfBirth, System.DateTime dateOfCalving, string tagNumber) {
            return base.Channel.AddCow(name, cowBreed, dateOfBirth, dateOfCalving, tagNumber);
        }
        
        public System.Threading.Tasks.Task<bool> AddCowAsync(string name, SoapRSIClient.CowService.CowBreed cowBreed, System.DateTime dateOfBirth, System.DateTime dateOfCalving, string tagNumber) {
            return base.Channel.AddCowAsync(name, cowBreed, dateOfBirth, dateOfCalving, tagNumber);
        }
        
        public bool RemoveCow(int id) {
            return base.Channel.RemoveCow(id);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveCowAsync(int id) {
            return base.Channel.RemoveCowAsync(id);
        }
        
        public bool UpdateCow(int id, string name, SoapRSIClient.CowService.CowBreed cowBreed, System.DateTime dateOfBirth, System.DateTime dateOfCalving, string tagNumber) {
            return base.Channel.UpdateCow(id, name, cowBreed, dateOfBirth, dateOfCalving, tagNumber);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCowAsync(int id, string name, SoapRSIClient.CowService.CowBreed cowBreed, System.DateTime dateOfBirth, System.DateTime dateOfCalving, string tagNumber) {
            return base.Channel.UpdateCowAsync(id, name, cowBreed, dateOfBirth, dateOfCalving, tagNumber);
        }
        
        public SoapRSIClient.CowService.Cow[] GetCowsNearToCalving() {
            return base.Channel.GetCowsNearToCalving();
        }
        
        public System.Threading.Tasks.Task<SoapRSIClient.CowService.Cow[]> GetCowsNearToCalvingAsync() {
            return base.Channel.GetCowsNearToCalvingAsync();
        }
        
        public SoapRSIClient.CowService.Cow[] GetCowsNearToDryOff() {
            return base.Channel.GetCowsNearToDryOff();
        }
        
        public System.Threading.Tasks.Task<SoapRSIClient.CowService.Cow[]> GetCowsNearToDryOffAsync() {
            return base.Channel.GetCowsNearToDryOffAsync();
        }
    }
}
